version: "3.8"
services:
 db:
  image: postgres:13.1
  environment:
   - POSTGRES_USER=$DB_USER
   - POSTGRES_PASSWORD=$DB_PASSWORD
  ports:
   - $DB_PORT:$DB_PORT
  volumes:
   - ./db/data:/var/lib/postgresql/data
  restart: always
  command: -p $DB_PORT
 api:
  depends_on:
   - db
  build: ./api
  environment:
   - NODE_ENV=$API_NODE_ENV
   - PORT=$API_PORT
   - PGHOST=db
   - PGPORT=$DB_PORT
   - PGUSER=$DB_USER
   - PGPASSWORD=$DB_PASSWORD
   - PGDATABASE=$DB_NAME
  ports:
   - $API_PORT:$API_PORT
  volumes:
   - ./api:/app
   - /app/node_modules
 ui:
  build: ./ui
  environment:
   - NODE_ENV=$UI_NODE_ENV
   - PORT=$UI_PORT
   - REACT_APP_API_HOST
  ports:
   - $UI_PORT:$UI_PORT
  volumes:
   - ./ui:/app
   - /app/node_modules
  stdin_open: true
